### ISSUE TITLE
Move to OpenSea API to query NFTs

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#315]
Currently we are using Covalent but it's often slow to resolve. Moving to OpenSea would give us more rich context (like price) and probably a more complete listing.

**Comment by Sekhmet** [comment]
@bonustrack API to [list NFTs](https://docs.opensea.io/reference/getting-assets) requires API key, can you [request API](https://docs.opensea.io/reference/request-an-api-key) key from OpenSea? Looks like they have manual approval process and doing this though Snapshot's email might get us the key faster.

**Comment by bonustrack** [comment]
@Sekhmet I've made a request 2 weeks ago with Snapshot email but got no reply, on their Discord there is many others in same situation, we should get the key at some point I'll do another request if no progress. This should not be a blocker for the integration, their API doesn't require API key if you use their testnet which is on Goerli, for us it will be ideal since our testnet is also on Goerli.
