### ISSUE TITLE
feat: add Histoire

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#338]
https://histoire.dev/guide/vue3/getting-started.html

**Comment by Dhaiwat10** [comment]
if you guys are accepting contributions from outside, would love to help out with this one!

**Comment by bonustrack** [comment]
Awesome, go for it @Dhaiwat10 :)

**Comment by j0hnfl0w** [comment]
@bonustrack there are still problems with tailwind and histoire, tried almost the same solution as in https://github.com/snapshot-labs/sx-ui/pull/341 but it wont work.
Then I tried to setup histoire with https://github.com/unocss/unocss and it works good, also migrated almost all tailwind config, so css experience and api are the same.

**Comment by Sekhmet** [comment]
It has been integrated.
