### ISSUE TITLE
Add infinite loading on proposals page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#360]
Currently on proposals page we only see the last 5 proposals, we should have a way to load all the proposals with infinite loading
https://testnet.snapshotx.xyz/#/0x07e6e9047eb910f84f7e3b86cea7b1d7779c109c970a39b54379c1f4fa395b28/proposals

**Comment by Sekhmet** [comment]
Duplicate of https://github.com/snapshot-labs/sx-ui/issues/357

:D

**Comment by bonustrack** [comment]
Ops my bad
