### ISSUE TITLE
feat: favorite space(s)

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#383]
- We should add a new button using `star` icon on the space overview page here:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16245250/213922903-6b0d1559-b34f-49a0-afb9-688e05cf0061.png">

- We should also change the icon to create a proposal on overview and proposals pages to `pencil-alt`.
- When someone click to favorite a space we should change the icon to a star filled, there isn't any star filled on Heroicons, this will require a custom SVG.
- We should store and update the list of favorite spaces on localStorage
- This should work unlogged too, the list should not be specific to the logged user (not like on snapshot.org).
- On the left bar we should see only the favorites spaces, the list should be updated instantly when adding / remove a space to favorites
<img width="677" alt="image" src="https://user-images.githubusercontent.com/16245250/213923671-1b244e05-847a-40b9-91af-eb623d18c6e2.png">

- Ideally we should make space draggable on the left bar and store the order in localStorage too.

**Comment by bonustrack** [comment]
Adding another requirement: when adding a space to favorite, the space should appear first on the left bar, not last.

**Comment by j0hnfl0w** [comment]
Yep, fixed it )
