### ISSUE TITLE
feat: populate execution with WalletConnect

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#386]
**This issue is made for hiring challenge only, if you do this challenge make the change in a forked repository, don't PR this repository.**

We should add a feature to be able to login as a DAO to dapps like Uniswap, with this account and network (Goerli): https://github.com/snapshot-labs/sx-ui/blob/master/src/helpers/space.json

- On the proposal creation page we should add a button "WalletConnect" in the execution section with a `login` icon see:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16245250/214299898-896af7ba-8dca-4dc6-a17c-92dd0386ff80.png">

- When we click on this button it should open a modal with a form to input a connection link like this:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/16245250/214301331-84e7b06d-e512-4fd5-955e-8e5067ec7257.png">

The connection link is used to connect SX UI to a dapp, you can get a connection link from any dapp supporting WalletConnect like Uniswap (on Goerli) here:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/16245250/214303430-3551845c-bfbe-4873-906f-42e61df11f5e.png">

- Once the user input a connection link and click confirm, we need to use WalletConnect SDK to log as the DAO into Uniswap. Here is an example on how to do that: https://github.com/snapshot-labs/guest/blob/master/src/composables/useWalletConnect.ts#L83-L86 This come from http://guest.so which is a simple app to be able to login with any account on dapps.
We can add a loading icon into the "Confirm" button while login is going on.

- Once login is done we should close the modal
- If the modal is open again, we should show the logged account (the DAO) and a logout button like this:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/16245250/214305603-6799f0e0-8d81-4d12-8852-275de56877ff.png">

- If we click logout, it should logout the DAO to the dapp and come back to the previous form with Connection link input.

- If we trigger a new transaction on the dapp it should populate the execution section with new transaction (you can test that by trying to do a swap on Uniswap for example), it would look like this:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/16245250/214306103-7f686ac0-baf3-42ed-993d-cc8ef800b3a7.png">

To be able to decode the transaction you may need to load the ABI of the contract using the function getABI like this: https://github.com/snapshot-labs/sx-ui/blob/9fb1d6d569846f7f8660402baa521a387c98a6f8/src/helpers/etherscan.ts

And use such function https://github.com/snapshot-labs/sx-ui/blob/93fe78006cdab11ff6adac620c66de43c87fec61/src/helpers/transactions.ts#L84-L85

- The transaction should be populated as a "Contract call" and be editable. You can try adding a transaction manually and edit it if you click on "Contract call", select "WETH" as contract with the method "approve", guy "You" and wad "1".

### Recommendations

Here is our short list of recommendations before you get started on the challenge:

- Learn about our [Codestyle](https://github.com/snapshot-labs/guidebook/wiki/Codestyle).
- Read the [Development guide](https://github.com/snapshot-labs/sx-ui#development-guide) for Snapshot UI.
- Watch the [video presentation](https://user-images.githubusercontent.com/16245250/217367936-f9cdf5a5-6c12-46c5-baaa-ea8aba678128.mp4) of the UI running locally.

**Comment by bonustrack** [comment]
**This issue is made for hiring challenge only, if you do this challenge make the change in a forked repository, don't PR this repository.**

**Comment by Sekhmet** [comment]
I haven't yet.

**Comment by Sekhmet** [comment]
@bonustrack do you have more context about the redesign? We don't want WC option at all in editor? I'm not sure how it's going to work.

1. We add button in Treasury page to build execution, you sign in, and keep adding transactions in app.
2. How do we know when to end (do we add button to finish and then move it to editor) or maybe it should be modal?

**Comment by bonustrack** [comment]
Here is some good example of a similar integration https://twitter.com/safe/status/1719346365472670125
