### ISSUE TITLE
feat: add ENS domain name resolver

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#389]
Currently on SX UI the spaces and profile contain a long address on URLs example:
https://snapshotx.xyz/#/0x07e6e9047eb910f84f7e3b86cea7b1d7779c109c970a39b54379c1f4fa395b28/proposal/70

We should implement a domain name resolver to be able to use a domain from ENS, Lens, Unstoppable domains and Starknet.id example:
https://snapshotx.xyz/#/fabien.eth
https://snapshotx.xyz/#/fabien.lens/proposal/70
https://snapshotx.xyz/#/fabien.crypto/treasury
https://snapshotx.xyz/#/profile/fabien.stark

On the UI we should convert the domain to an address with a network prefix. Lens is on Polygon, Stark on StarkNet and for .eth we should recognize only mainnet domains.

**Comment by Sekhmet** [comment]
We will need to remove dependency on networkID prefix from URL in some places of the app.

Currently we don't really support any of the networks mentioned here (no support for polygon and eth mainnet, Starknet is broken because the contracts now have incompatible API). Does it mean we will need to add support for those networks before we can implement this PR? I could add just the resolvers but they will be pointing to broken URLs and won't be possible to test.

**Comment by bonustrack** [comment]
I imagine for a first step we can try to add support for ENS assuming we use Goerli as default network where fabien.eth is converted to `gor:0x12345...` based on Goerli registry, then later we can switch to mainnet by default for ENS. 

The owner of the NFT can not be the space itself cuz the space contract is not a treasury (can't transfer fund directly) if someone send the NFT to the space contract the space wont be able to transfer it anymore. We can identify the space with the ETH address defined on the ENS profile instead.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/16245250/236790804-6390fcdd-6f49-4b6e-8de6-3cafe3015096.png">

I just created this ENS domain on Goerli: https://app.ens.domains/discopolo.eth
The ENS ETH address is linked to this space: https://snapshotx.xyz/#/gor:0x5acb7858d0441f618fa25cd81dd1b22d1ed90876

When we go to https://snapshotx.xyz/#/discopolo.eth the UI should act like we are on: https://snapshotx.xyz/#/gor:0x5acb7858d0441f618fa25cd81dd1b22d1ed90876

**Comment by bonustrack** [comment]
I'm reducing the scope of this issue to be just about resolving ENS domains since others networks are not supported atm will be hard to test.

**Comment by bonustrack** [comment]
I imagine we can have a store to keep mapping of ENS name to space network + address to not query this information on each page but yes there will need to be some refactoring to assume data may come async. I've tested your branch it looks a bit slow, I can see request being sent to nodes with `eth_chainId` this is something usually that come from the default provider and not `StaticJsonRpcProvider` not sure why we get these requests but if we can remove them that should speed up the UX.
