### ISSUE TITLE
bug: sidebar spaces are not clickable

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#414]
It's not possible to click on a space from the sidebar on a mobile. This bug was introduced in #383

**Comment by j0hnfl0w** [comment]
Hm, works good on iOS safari/chrome, a bit laggy in desktop device emulator.https://user-images.githubusercontent.com/97898172/217582720-e65d5c5e-3be4-45b2-80e4-0e8175be1d2a.MOV

**Comment by j0hnfl0w** [comment]
Found this issue with Android chrome, dragging works fine but its hard to click

**Comment by bonustrack** [comment]
@j0hnfl0w I'm able to drag the icons too but nothing happen when I click, also require 2 clicks to close the menu after trying to click on space. This is using Android 13 with Chrome 109.0.5414.118.

**Comment by j0hnfl0w** [comment]
Yep, found a couple of issues with vuedraggable:
https://github.com/SortableJS/vue.draggable.next/issues/178
https://github.com/SortableJS/vue.draggable.next/issues/174
https://github.com/SortableJS/vue.draggable.next/issues/61
Will fix, now
