### ISSUE TITLE
feat: display total support for each choices

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#434]
Currently on a proposal we show only progress bars for the scores, we should show the amount of voting power in support for each choice "For" "Against" and "Abstain".
**Design TBD**

**Comment by bonustrack** [comment]
Can be like this for now:
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/16245250/221014618-4fe02f64-850b-4883-9f39-60536e77c8db.png">

**Comment by Sekhmet** [comment]
@bonustrack what if one choice has low support and its total support label won't fit?


![Image](https://user-images.githubusercontent.com/1968722/221811718-f46c8c02-c978-4e06-b58d-fa3218f8dabb.png)


There is also case of quorum: if quorum is 1M and currently there are 1% votes For then For bar will be 1% of the total width, not enough to fit any text.

**Comment by bonustrack** [comment]
@Sekhmet You could show only the percentage and vp for the choice with most support and then show the others at the same place on mouse over like this:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/16245250/221873392-fed0274c-a5fc-4bc0-a39a-367a91066186.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/16245250/221873635-2d3cc698-b179-4d3a-abba-814d7bebaa2a.png">

**Comment by Sekhmet** [comment]
@bonustrack is it going to work like this in all cases, or only when other options won't fit otherwise?

**Comment by bonustrack** [comment]
For all case @Sekhmet
