### ISSUE TITLE
feat: make it possible to select "No treasury" in Space form

### ISSUE THREAD

**Issue by Sekhmet** [snapshot-labs/sx-ui#480]
It should be possible to select No treasury in Space form (create and edit):
![image](https://user-images.githubusercontent.com/1968722/223200248-801e9e23-68d6-4199-9be2-ca9da7e92abb.png)

**Comment by j0hnfl0w** [comment]
@Sekhmet so walletNetwork can be null or something like "none"?

**Comment by Sekhmet** [comment]
I think ideally it would be null.
