### ISSUE TITLE
style: NFT list should have fixed width

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#497]
On the treasury page, the NFT should have a fixed width, currently on large screen it show way too big images
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/16245250/224366995-747e1f24-2728-4bb9-9e3c-decf861b5b9b.png">
Width can be 120px (similar than on send NFT modal)

**Comment by Sekhmet** [comment]
@bonustrack it uses 6 column layout, on big screen should it stick to 6 columns (and make whole grid smaller) or should it become 8 grid for example (with same size grid, but just smaller NFTs)?

**Comment by bonustrack** [comment]
@Sekhmet It's better to have a fixed width rather than a dynamic grid with columns based on the size of the screen. It's not a problem if a row doesn't end at the end of the main content.
