### ISSUE TITLE
bug: voting power showing NaN

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#550]
On this space: https://snapshotx.xyz/#/gor:0x65e4329e8c0fba31883b98e2cf3e81d3cdcac780/proposals
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/16245250/229889587-72dd582e-a83e-48fc-b239-0956a7054c48.png">

**Comment by Sekhmet** [comment]
It's because this PR is not merged yet: https://github.com/snapshot-labs/sx-ui/pull/547

**Comment by Sekhmet** [comment]
Fixed after #547
