### ISSUE TITLE
bug: contacts page should appear unlogged

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#568]
The contact page does not depend on user logged, currently if I open the page unlogged the page would be empty, we should instead show the list of contact.
https://snapshotx.xyz/#/settings/contacts

**Comment by j0hnfl0w** [comment]
To get to contacts we also need to show settings button here for unlogged user
![image](https://user-images.githubusercontent.com/97898172/233344794-42cb7fff-94d5-4bc8-a98d-6290a783dad7.png)

**Comment by j0hnfl0w** [comment]
@bonustrack wdyt?

**Comment by bonustrack** [comment]
@j0hnfl0w Ideally it should.be accessible by unlogged users but I'm not sure about the UX, currently unlogged users wont see this modal and we dont want to add additional step to login.

**Comment by j0hnfl0w** [comment]
Yeah so maybe we need to add some button to access to contacts for unlogged users somewhere.
How unlogged user can use contacts?
