### ISSUE TITLE
feat: input for duration should show days, hours and minutes

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#597]
The input with duration like min duration, max duration, timelock delay should be divided in 3 input with days hours and minutes

<img width="640" alt="image" src="https://user-images.githubusercontent.com/16245250/234905511-15c085bf-73cc-4756-a2e2-27ff26abfd6c.png">

**Comment by j0hnfl0w** [comment]
or it can be one date input to select end date with calendar

**Comment by Sekhmet** [comment]
> Can it be one date input to select end date with calendar?

It's duration not a date.

**Comment by j0hnfl0w** [comment]
yeah it's a duration, but from the user perspective can it be like "we want to finish voting on a Sunday evening" so user need to calculate duration to specific date.

**Comment by bonustrack** [comment]
How would that work, this is a global settings for the space not for a specific proposal

**Comment by j0hnfl0w** [comment]
So all proposals in a space has the same duration? If so setting a date is pointless.

**Comment by j0hnfl0w** [comment]
Ah yeah it is for min/max duration, sorry
