### ISSUE TITLE
feat: add link to the space from the proposal page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#607]
Design TBD

**Comment by Sekhmet** [comment]
@bonustrack can I use the UI from this issue for this?
https://github.com/snapshot-labs/sx-ui/issues/724

![image](https://github.com/snapshot-labs/sx-ui/assets/1968722/e362a0cf-a145-417e-abd7-d576ac7b148d)

**Comment by bonustrack** [comment]
Yes
