### ISSUE TITLE
feat: allows for space or proposal without execution

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#621]
It should be possible to create a space without any execution strategy, and it should be possible to create a proposal without any execution (even if the space has execution some strategies)

**Comment by bonustrack** [comment]
To my understanding we need to pass an execution parameter on the contract when we create a proposal, but this param can be empty, right @pscott? Or do we need some smart contract changes?

**Comment by pscott** [comment]
You can definitely create a proposal with an execution strategy set to `0` (so not "empty" but set to 0), but of course you won't be able to call the `execute` function.
We could make a special case where `execute` doesn't actually `execute` anything if `executionStrategy.address == 0` (one `if` condition to add in the space contract).

**Comment by pscott** [comment]
For code context:

1) In the `propose` function we store the `executionStrategy.addr` here: https://github.com/snapshot-labs/sx-evm/blob/b42170b3e50eeefa2c1886536d1bf9fa2c51ae11/src/Space.sol#L373

2) In the `execute` function we call the `execute` method on the contract that we stored previously... if you set it to 0, we will call `execute` on contract located at `0x000` (which doesn't exist ofc): 
https://github.com/snapshot-labs/sx-evm/blob/b42170b3e50eeefa2c1886536d1bf9fa2c51ae11/src/Space.sol#L437
