### ISSUE TITLE
Unable to login with uBlock Origin (ad blocker extension)

### ISSUE THREAD

**Issue by Todmy** [snapshot-labs/sx-ui#623]
### The problem:
Cannot log in to https://snapshotx.xyz/#/ probably because of the ad blocker. After a try to log in, I got an infinite loading animation on the button "Connect wallet"

### Video:
https://user-images.githubusercontent.com/7693369/235634841-889d9fd2-acfd-4093-8c93-91aafb0c26d7.mov

### Environment:
- Apple M1, macOS Version 13.3.1
- Chrome 112
- ad blocker extension: uBlock Origin

**Comment by ChaituVR** [comment]
We need to change the domain to `https://rpc.snapshot.org/` instead of `brovider.xyz`
