### ISSUE TITLE
bug: navigation broken on small screen

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#636]
If you go on this page on mobile:
https://snapshotx.xyz/#/gor:0x2b5e7ac0e76dcb41d3e506d58c9997d42d133e07

Then click on the logo to get back to homepage you'll get this and break navigation:
<img width="500" alt="image" src="https://github.com/snapshot-labs/sx-ui/assets/16245250/7e3f1c63-6bbb-45ba-879c-4c5b076ed6f1">

**Comment by Sekhmet** [comment]
I included the fix in https://github.com/snapshot-labs/sx-ui/pull/637 as it has most of the refactoring done for it.
