### ISSUE TITLE
feat: modal to delegate voting power

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#656]
We have a button on top right of the delegate page to delegate voting power but currently it's not active, we should make it.

**Comment by pudgefury** [comment]
Could I pick this?
Best regards

**Comment by bonustrack** [comment]
@pudgefury Sure feel free, I've assigned you to the issue. 

Here is more specs:

- We need to add 2 new inputs in the space profile to define the delegation contract address and the chain. This should appear in space creation and edit profile modal. And be stored in space metadata as `delegation_address` with value in this format `gor:0x1234...`
- Add delegate modal with an input "Delegate" and button confirm. Design should be similar than others modals with input like add contact or send contract call.
- We should have a validation in the delegate input to accept only address.
- If the delegation address and chain are not defined the button to delegate should not appear.
- When confirm a new delegate, it should close the modal and add a transaction as pending.

**Comment by pudgefury** [comment]
Do you have design for that?

**Comment by bonustrack** [comment]
@pudgefury 
<img width="477" alt="image" src="https://github.com/snapshot-labs/sx-ui/assets/16245250/93602dbd-2fa8-49ff-b868-bd3bab2998f6">

**Comment by pudgefury** [comment]
Could we discuss more detail about this task?

Do you have telegram where can i contact?

**Comment by bonustrack** [comment]
You can contact me on Telegram my username is "bonustrack"
