### ISSUE TITLE
bug(sx-sn): proposal is not updated after vote

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#748]
I voted on this proposal, if you open the vote modal you will see my vote, but on the results or vote count it's not showing up
https://snapshotx.xyz/#/sn-tn:0x04b1953ac6bbe7a162d1afca0065bc82ba707501acbc01774cc1cf59721da6df/proposal/2

**Comment by bonustrack** [comment]
Also something wrong with the space vote counter, currently it's showing 250+ votes https://snapshotx.xyz/#/sn-tn:0x04b1953ac6bbe7a162d1afca0065bc82ba707501acbc01774cc1cf59721da6df

**Comment by Sekhmet** [comment]
It's because sx-api is failing due to VP overflow on this space:
<img width="1847" alt="image" src="https://github.com/snapshot-labs/sx-ui/assets/1968722/820469ad-77a1-4402-9f44-eac8fd026dd8">

This will be fixed once ORM is used as we changed it to BigInt there.
