### ISSUE TITLE
chore: hide "Your voting power" and "Cast your vote" sections if proposal ended

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#767]
On the proposal page, we should hide "Your voting power" and "Cast your vote" sections once the proposal ended (with max end)

**Comment by samuveth** [comment]
@Sekhmet any reason you unassigned this issue? PR is already open

**Comment by Sekhmet** [comment]
Sorry, it was unassigned when PR was submitted so I wanted to assign it to you and muscle memory took over and I assigned myself (and later you), and instead of removing myself I removed you by mistake.
