### ISSUE TITLE
feat: move to Mixpanel

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#768]
We should replace Google Analytics with Mixpanel with geolocation disabled see more info here: https://docs.mixpanel.com/docs/tracking/how-tos/privacy-friendly-tracking#disabling-geolocation
Here is the project token `47b43858cf6fe9376f8deddda52cbaaf`

**Comment by Sekhmet** [comment]
@samuveth 
https://github.com/snapshot-labs/sx-ui/blob/be07543e2216110150124d7ae435c1f9bc46c75d/src/main.ts#L28-L44
