### ISSUE TITLE
feat: support Starknet mainnet

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#823]
We need to add support for Starknet mainnet in our UI. This will require some change on SX.js, SX-UI, SX-API and Mana most likely. I can help setup the server, we will move SN testnet API to https://testnet.api-1.snapshotx.xyz and use https://api-1.snapshotx.xyz for SN mainnet.

**Comment by Sekhmet** [comment]
@bonustrack sx.js already has mainnet config so should be good to go. So is mana (just needs to get account set up on mainnet and get funded).

Only sx-api and sx-ui should need changes, I will work on those and we can deploy updated sx-api.

**Comment by bonustrack** [comment]
Got it sound great!

**Comment by bonustrack** [comment]
This endpoint for testnet works now: https://testnet-api-1.snapshotx.xyz
