### ISSUE TITLE
SX-UI: create proposal on Snapshot

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-ui#849]
# SX-UI: offchain proposal editor

# Framing

- Give users the ability to create proposals on offchain spaces from SX-UI.

# Design/UX

- We should reuse, to the extent possible, the same UI components used for onchain voting.
- We’ll enforce a common voting delay and voting period across the space’s proposals, so there’s no need to show options for that within the proposal editor.
- In the case of offchain space proposals, we will need to add a dropdown for selecting voting type (basic, single choice, approval).
    - If type is not basic, then we will need a way to add choices
    - Designer’s input will be needed to implement this part (below is just for reference).

![Image](https://github.com/snapshot-labs/sx-ui/assets/1968722/134212e6-5974-4b08-8d62-3c1c5284ccf3)

You can test here on second step of proposal creation:

https://testnet.snapshot.org/#/testsnap.eth/create

# Technical spec

1. I recommend starting with just basic voting (For, Against, Abstain) as that's voting types we support right now -> we will likely need some design input for both editor and voting part).
2. We will need remove this check so we can access editor: https://github.com/snapshot-labs/sx-monorepo/blob/5279ba93d606c5744891307509eb0e3906b1c1e9/apps/ui/src/views/Space/Overview.vue#L66
3. Editor checks for VP before user can create proposal. SX spaces have separate strategies for voting and proposing (I'm not familiar with Snapshot v1) - we will need to fill in proper strategies there (to either use the same, or different values if Snapshot v1 has different strategies for proposing as well) - will need to adjust types to make sense: https://github.com/snapshot-labs/sx-monorepo/blob/75315e017c7361c93ef7d5a8d5303f5fc3ef4351/apps/ui/src/networks/offchain/api/index.ts#L75-L77
4. Next step will be to add `propose` method (remember to change useActions to use `getNetwork` instead of `getReadWriteNetwork` for propose), similar to `vote` and add support to `propose` method in sx.js (similar as vote). https://github.com/snapshot-labs/sx-monorepo/blob/737bfe872936f8372490a56aae109075a56c7c9d/apps/ui/src/networks/offchain/actions.ts#L32-L52

**Comment by wa0x6e** [comment]
We're not allowing user to choose the voting period and delay here. What arbitrary values should we set if the space did not set them ?
